### ISSUE TITLE
new bug:Call to undefined function panelHeading()

### ISSUE THREAD

**Issue by argb** [bishopb/laravel-forums#9]
there is no definition of function panelHeading, what does this function do?
this is a good project,but need more tests.

**Comment by woodytang** [comment]
i got the same exception too:
Call to undefined function panelHeading()

/Users/tangsi/Documents/laravelbase/laravelbase/vendor/bishopb/laravel-forums/src/views/themes/default/views/modules/categories.php

**Comment by dantemple** [comment]
I seem to get the same error

**Comment by bishopb** [comment]
`composer update bishopb/laravel-forums` to get the latest (0.1.4), which seems to fix the issue.
